language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t gkozlovskii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gkozlovskii/docker-react npm run test -- --coverage